{% set name = "schedule" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1654cf70860a6d4d58236c98b0f1bb71521cc2a4bbf031b6cc39c96e77d59a91

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - schedule

about:
  home: https://github.com/dbader/schedule
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Job scheduling for humans.
  doc_url: https://schedule.readthedocs.io/

extra:
  recipe-maintainers:
    - tschoonj
